package com.merigasparyan.jmp.parkingserviceapi.enums;

public enum Permission {
    CREATE_ACCOUNT,
    CREATE_BOOKING,
    VIEW_OWN_BOOKING,
    CANCEL_OWN_BOOKING,
    PARK_IN_SPOT,
    RELEASE_SPOT,

    VIEW_AVAILABLE_SPOT,

    CREATE_SPOT,
    UPDATE_SPOT,
    DELETE_SPOT,

    VIEW_ALL_BOOKINGS,
    CANCEL_BOOKING,

    INVITE_RESIDENT,
    REMOVE_RESIDENT,
    INVITE_GUEST,
    REMOVE_GUEST,

    VIEW_CURRENT_BOOKINGS,
    CHANGE_BOOKING_STATUS,

    CREATE_GUEST_BOOKING,

    CREATE_COMMUNITY,
    UPDATE_COMMUNITY,
    DELETE_COMMUNITY,
    ASSIGN_COMMUNITY_MANAGER,
    MANAGE_USERS
}
